namespace TodoApi.Domain.Entities; // Defines the namespace for domain entities (core business objects)

public class TodoItem // Represents one task in your system (domain model)
{
    public int Id { get; set; } // Unique identifier for the task. Generated by repository.

    public string Title { get; set; } = string.Empty; // Short title/text for the task. Cannot be null because of default value.

    public string? Description { get; set; } // Optional detailed text. The '?' means it's allowed to be null.

    public bool IsCompleted { get; set; } // Tracks if the task has been finished (true = done, false = not done).

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow; // When the task was created. Automatically filled with current UTC time.

    public DateTime? DueDate { get; set; } // Optional deadline for the task. If null, the task has no deadline.
}
